version: '2'
services:
    ecommerce-app:
        image: ecommerce
        external_links:
            - ecommerce-mysql:mysql
            - ecommerce-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    ecommerce-mysql:
        extends:
            file: mysql.yml
            service: ecommerce-mysql
    ecommerce-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ecommerce-elasticsearch
